### ISSUE TITLE
.babelrc changes are not picked up unless you clear packager cache

### ISSUE THREAD

**Issue by gaearon** [mjohnston/react-native-webpack-server#63]
I don't know enough about Packager but I just found out the hard way that adding `.babelrc` and later changing it has zero effect unless you also delete some temp directories.

This comment explains what to do: https://github.com/facebook/react-native/issues/1924#issuecomment-120170512

I'm not sure whether we should
- do this from code
- wait for RN to do this
- warn about it in README

but I for sure know I spent three hours on this.

:-)

**Comment by alejomendoza** [comment]
this is such a pain in the ass issue!

**Comment by gaearon** [comment]
For now, just don't use `.babelrc`.
You can provide Babel configuration in Webpack config, like in the examples.

**Comment by elliottsj** [comment]
I'll add a note in the README this evening

**Comment by elliottsj** [comment]
Added note: https://github.com/mjohnston/react-native-webpack-server/commit/3ad235c5168c63a9cfde71b8ea178520c6cefee0

Let's keep this open until it's truly fixed in RN 0.12

**Comment by adaojunior** [comment]
Im running RN 0.12, how do I clear the cache ?
I tried `npm start reset-cache` and `sh ./node_modules/react-native/packager/packager.sh reset-cache` and still nothing.
I'm on windows.

**Comment by elliottsj** [comment]
@adaojunior Try `./node_modules/react-native/packager/packager.sh start --resetCache`

**Comment by adaojunior** [comment]
@elliottsj I think it may be working because it is taking longer the first time I start the packager and it transform it after, but I'm still getting a `Unexpected Error`, I'm trying to use es6.modules.

```
export default Root extends React.Component{
  render(){
    return (
      <Text>Hello World!</Text>
    );
  }
}
```

but I'm getting an error in the export line.

**Comment by gaearon** [comment]
> export default Root

Seems like you're missing `class`: `export default class Root`.

**Comment by adaojunior** [comment]
@gaearon yeah thank you, it's working now :D
that is just 40 minutes of my life that I wont get back lol

**Comment by oliversisson** [comment]
"Please start using `--reset-cache` instead. We'll deprecate this argument soon."
